version: '3.4'

services:
  webapp:
    image: dotnet-mvc:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CommerceDB=Host=db;Database=mydb;Username=myuser;Password=mypassword
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
